name: Quality Check

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/workflows/build.yml"

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "yarn" # caches the yarn cache folder not node_modules

      - name: Prepare
        run: yarn install --frozen-lockfile

      - name: Quality Check
        run: yarn qc
