name: Quality Check

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/workflows/build.yml"

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Check
        run: yarn test
