name: Build test

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Prepare
        run: npm install
      - name: Build test
        run: npm run build
      - name: Lint test
        run: npm run lint
