name: Quality Check

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/workflows/ci.yml"

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Prepare
        run: yarn install
      - name: Lint test
        run: yarn run lint
